package org.openpm

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
	
	static authenticatedActions = [
		[controller: 'project', roles: ['ROLE_ADMIN', 'ROLE_USER', 'ROLE_PROJECT_MANAGER']]
	]

	
    def filters = {
		// Ensure that all controllers and actions require an authenticated user,
		auth(controller: "*", action: "*") {
			before = {
				// except for the "help" controller and the "error" controller
				if (controllerName == "error") {
					return true
				}
				// This just means that the user must be authenticated. He does
				// not need any particular role or permission.
				accessControl { true }
			}
		}
    }
}
